"""Initial migration

Revision ID: 09da7d4a7403
Revises: 
Create Date: 2025-11-19 18:39:32.484937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09da7d4a7403'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tld', sa.String(length=50), nullable=False),
    sa.Column('global_rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_domains_global_rank'), 'domains', ['global_rank'], unique=False)
    op.create_index(op.f('ix_domains_tld'), 'domains', ['tld'], unique=False)
    op.create_table('statistics_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_date', sa.DateTime(), nullable=False),
    sa.Column('statistics_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_date')
    )
    op.create_table('scan_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('scan_date', sa.DateTime(), nullable=False),
    sa.Column('scan_status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_results_scan_date'), 'scan_results', ['scan_date'], unique=False)
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_result_id', sa.Integer(), nullable=True),
    sa.Column('signature_algorithm', sa.String(length=100), nullable=True),
    sa.Column('public_key_algorithm', sa.String(length=100), nullable=True),
    sa.Column('public_key_size', sa.Integer(), nullable=True),
    sa.Column('issuer', sa.String(length=255), nullable=True),
    sa.Column('ca_type', sa.String(length=50), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['scan_result_id'], ['scan_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cipher_suites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_result_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_exchange', sa.String(length=100), nullable=True),
    sa.Column('authentication', sa.String(length=100), nullable=True),
    sa.Column('encryption', sa.String(length=100), nullable=True),
    sa.Column('mac', sa.String(length=100), nullable=True),
    sa.Column('is_forward_secret', sa.Boolean(), nullable=True),
    sa.Column('is_weak', sa.Boolean(), nullable=True),
    sa.Column('tls_version', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['scan_result_id'], ['scan_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geo_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_result_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('country_name', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.ForeignKeyConstraint(['scan_result_id'], ['scan_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pqc_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_result_id', sa.Integer(), nullable=True),
    sa.Column('is_supported', sa.Boolean(), nullable=False),
    sa.Column('ml_kem_512', sa.Boolean(), nullable=True),
    sa.Column('ml_kem_768', sa.Boolean(), nullable=True),
    sa.Column('ml_kem_1024', sa.Boolean(), nullable=True),
    sa.Column('supported_suites', sa.Text(), nullable=True),
    sa.Column('algorithm_combinations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scan_result_id'], ['scan_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tls_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_result_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('is_supported', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scan_result_id'], ['scan_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tls_versions')
    op.drop_table('pqc_info')
    op.drop_table('geo_locations')
    op.drop_table('cipher_suites')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_scan_results_scan_date'), table_name='scan_results')
    op.drop_table('scan_results')
    op.drop_table('statistics_cache')
    op.drop_index(op.f('ix_domains_tld'), table_name='domains')
    op.drop_index(op.f('ix_domains_global_rank'), table_name='domains')
    op.drop_table('domains')
    # ### end Alembic commands ###
