"""Add certificate_pem and subject to certificates

Revision ID: 6ac06ef47c0a
Revises: 09da7d4a7403
Create Date: 2025-11-19 19:18:59.441483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ac06ef47c0a'
down_revision: Union[str, Sequence[str], None] = '09da7d4a7403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('subject', sa.String(length=255), nullable=True))
    op.add_column('certificates', sa.Column('certificate_pem', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificates', 'certificate_pem')
    op.drop_column('certificates', 'subject')
    # ### end Alembic commands ###
